version: 1.0
environment_variables:
    plaintext:
        "INPUT_FILE": "VPCSetup.yaml"
        "S3_BUCKET": "codebuildbucketsm"
phases:
    build:
       commands:
            - aws cloudformation package --template $INPUT_FILE --s3-bucket $S3_BUCKET --output-template output.yaml
        artifacts:
            files:
                - output.yaml
