version: 0.2
phases:
  build:
    commands:
        - export BUCKET=demo-app-581209585450-us-east-1-demoapp1
        - aws cloudformation package --template VPCSetup.yaml --s3-bucket $BUCKET --output-template output.yaml
artifacts:
  type: zip
  files:
    - VPCSetup.yaml
    - output.yaml
